export default {
  rows: [
    [
      {
        code: 'Backquote',
        size: 'small',
        actionkey: false,
        en: { key: '`', capsAndKey: '`', shiftAndKey: '~' },
        ru: { key: 'ё', capsAndKey: 'Ё', shiftAndKey: 'Ё' },
      },
      {
        code: 'Digit1',
        size: 'small',
        actionkey: false,
        en: { key: '1', capsAndKey: '1', shiftAndKey: '!' },
        ru: { key: '1', capsAndKey: '1', shiftAndKey: '!' },
      },
      {
        code: 'Digit2',
        size: 'small',
        actionkey: false,
        en: { key: '2', capsAndKey: '2', shiftAndKey: '@' },
        ru: { key: '2', capsAndKey: '2', shiftAndKey: '"' },
      },
      {
        code: 'Digit3',
        size: 'small',
        actionkey: false,
        en: { key: '3', capsAndKey: '3', shiftAndKey: '#' },
        ru: { key: '3', capsAndKey: '3', shiftAndKey: '№' },
      },
      {
        code: 'Digit4',
        size: 'small',
        actionkey: false,
        en: { key: '4', capsAndKey: '4', shiftAndKey: '$' },
        ru: { key: '4', capsAndKey: '4', shiftAndKey: ';' },
      },
      {
        code: 'Digit5',
        size: 'small',
        actionkey: false,
        en: { key: '5', capsAndKey: '5', shiftAndKey: '%' },
        ru: { key: '5', capsAndKey: '5', shiftAndKey: '%' },
      },
      {
        code: 'Digit6',
        size: 'small',
        actionkey: false,
        en: { key: '6', capsAndKey: '6', shiftAndKey: '^' },
        ru: { key: '6', capsAndKey: '6', shiftAndKey: ':' },
      },
      {
        code: 'Digit7',
        size: 'small',
        actionkey: false,
        en: { key: '7', capsAndKey: '7', shiftAndKey: '&' },
        ru: { key: '7', capsAndKey: '7', shiftAndKey: '?' },
      },
      {
        code: 'Digit8',
        size: 'small',
        actionkey: false,
        en: { key: '8', capsAndKey: '8', shiftAndKey: '*' },
        ru: { key: '8', capsAndKey: '8', shiftAndKey: '*' },
      },
      {
        code: 'Digit9',
        size: 'small',
        actionkey: false,
        en: { key: '9', capsAndKey: '9', shiftAndKey: '(' },
        ru: { key: '9', capsAndKey: '9', shiftAndKey: '(' },
      },
      {
        code: 'Digit0',
        size: 'small',
        actionkey: false,
        en: { key: '0', capsAndKey: '0', shiftAndKey: ')' },
        ru: { key: '0', capsAndKey: '0', shiftAndKey: ')' },
      },
      {
        code: 'Minus',
        size: 'small',
        actionkey: false,
        en: { key: '-', capsAndKey: '-', shiftAndKey: '_' },
        ru: { key: '-', capsAndKey: '-', shiftAndKey: '_' },
      },
      {
        code: 'Equal',
        size: 'small',
        actionkey: false,
        en: { key: '=', capsAndKey: '=', shiftAndKey: '+' },
        ru: { key: '=', capsAndKey: '=', shiftAndKey: '+' },
      },
      {
        code: 'Backspace',
        size: 'middle',
        actionkey: true,
        en: { key: 'Backspace', capsAndKey: 'Backspace', shiftAndKey: 'Backspace' },
        ru: { key: 'Backspace', capsAndKey: 'Backspace', shiftAndKey: 'Backspace' },
      },
    ],
    [
      {
        code: 'Tab',
        size: 'small',
        actionkey: true,
        en: { key: 'Tab', capsAndKey: 'Tab', shiftAndKey: 'Tab' },
        ru: { key: 'Tab', capsAndKey: 'Tab', shiftAndKey: 'Tab' },
      },
      {
        code: 'KeyQ',
        size: 'small',
        actionkey: false,
        en: { key: 'q', capsAndKey: 'Q', shiftAndKey: 'Q' },
        ru: { key: 'й', capsAndKey: 'Й', shiftAndKey: 'Й' },
      },
      {
        code: 'KeyW',
        size: 'small',
        actionkey: false,
        en: { key: 'w', capsAndKey: 'W', shiftAndKey: 'W' },
        ru: { key: 'ц', capsAndKey: 'Ц', shiftAndKey: 'Ц' },
      },
      {
        code: 'KeyE',
        size: 'small',
        actionkey: false,
        en: { key: 'e', capsAndKey: 'E', shiftAndKey: 'E' },
        ru: { key: 'у', capsAndKey: 'У', shiftAndKey: 'У' },
      },
      {
        code: 'KeyR',
        size: 'small',
        actionkey: false,
        en: { key: 'r', capsAndKey: 'R', shiftAndKey: 'R' },
        ru: { key: 'к', capsAndKey: 'К', shiftAndKey: 'К' },
      },
      {
        code: 'KeyT',
        size: 'small',
        actionkey: false,
        en: { key: 't', capsAndKey: 'T', shiftAndKey: 'T' },
        ru: { key: 'е', capsAndKey: 'Е', shiftAndKey: 'Е' },
      },
      {
        code: 'KeyY',
        size: 'small',
        actionkey: false,
        en: { key: 'y', capsAndKey: 'Y', shiftAndKey: 'Y' },
        ru: { key: 'н', capsAndKey: 'Н', shiftAndKey: 'Н' },
      },
      {
        code: 'KeyU',
        size: 'small',
        actionkey: false,
        en: { key: 'u', capsAndKey: 'U', shiftAndKey: 'U' },
        ru: { key: 'г', capsAndKey: 'Г', shiftAndKey: 'Г' },
      },
      {
        code: 'KeyI',
        size: 'small',
        actionkey: false,
        en: { key: 'i', capsAndKey: 'I', shiftAndKey: 'I' },
        ru: { key: 'ш', capsAndKey: 'Ш', shiftAndKey: 'Ш' },
      },
      {
        code: 'KeyO',
        size: 'small',
        actionkey: false,
        en: { key: 'o', capsAndKey: 'O', shiftAndKey: 'O' },
        ru: { key: 'щ', capsAndKey: 'Щ', shiftAndKey: 'Щ' },
      },
      {
        code: 'KeyP',
        size: 'small',
        actionkey: false,
        en: { key: 'p', capsAndKey: 'P', shiftAndKey: 'P' },
        ru: { key: 'з', capsAndKey: 'З', shiftAndKey: 'З' },
      },
      {
        code: 'BracketLeft',
        size: 'small',
        actionkey: false,
        en: { key: '[', capsAndKey: '[', shiftAndKey: '{' },
        ru: { key: 'х', capsAndKey: 'Х', shiftAndKey: 'Х' },
      },
      {
        code: 'BracketRight',
        size: 'small',
        actionkey: false,
        en: { key: ']', capsAndKey: ']', shiftAndKey: '}' },
        ru: { key: 'ъ', capsAndKey: 'Ъ', shiftAndKey: 'Ъ' },
      },
      {
        code: 'Backslash',
        size: 'small',
        actionkey: false,
        en: { key: '\\', capsAndKey: '\\', shiftAndKey: '|' },
        ru: { key: '\\', capsAndKey: '\\', shiftAndKey: '/' },
      },
      {
        code: 'Delete',
        size: 'small',
        actionkey: true,
        en: { key: 'Del', capsAndKey: 'Del', shiftAndKey: 'Del' },
        ru: { key: 'Del', capsAndKey: 'Del', shiftAndKey: 'Del' },
      },
    ],
    [
      {
        code: 'CapsLock',
        size: 'middle',
        actionkey: true,
        en: { key: 'CapsLock', capsAndKey: 'CapsLock', shiftAndKey: 'CapsLock' },
        ru: { key: 'CapsLock', capsAndKey: 'CapsLock', shiftAndKey: 'CapsLock' },
      },
      {
        code: 'KeyA',
        size: 'small',
        actionkey: false,
        en: { key: 'a', capsAndKey: 'A', shiftAndKey: 'A' },
        ru: { key: 'ф', capsAndKey: 'Ф', shiftAndKey: 'Ф' },
      },
      {
        code: 'KeyS',
        size: 'small',
        actionkey: false,
        en: { key: 's', capsAndKey: 'S', shiftAndKey: 'S' },
        ru: { key: 'ы', capsAndKey: 'Ы', shiftAndKey: 'Ы' },
      },
      {
        code: 'KeyD',
        size: 'small',
        actionkey: false,
        en: { key: 'd', capsAndKey: 'D', shiftAndKey: 'D' },
        ru: { key: 'в', capsAndKey: 'В', shiftAndKey: 'В' },
      },
      {
        code: 'KeyF',
        size: 'small',
        actionkey: false,
        en: { key: 'f', capsAndKey: 'F', shiftAndKey: 'F' },
        ru: { key: 'а', capsAndKey: 'А', shiftAndKey: 'А' },
      },
      {
        code: 'KeyG',
        size: 'small',
        actionkey: false,
        en: { key: 'g', capsAndKey: 'G', shiftAndKey: 'G' },
        ru: { key: 'п', capsAndKey: 'П', shiftAndKey: 'П' },
      },
      {
        code: 'KeyH',
        size: 'small',
        actionkey: false,
        en: { key: 'h', capsAndKey: 'H', shiftAndKey: 'H' },
        ru: { key: 'р', capsAndKey: 'Р', shiftAndKey: 'Р' },
      },
      {
        code: 'KeyJ',
        size: 'small',
        actionkey: false,
        en: { key: 'j', capsAndKey: 'J', shiftAndKey: 'J' },
        ru: { key: 'о', capsAndKey: 'О', shiftAndKey: 'О' },
      },
      {
        code: 'KeyK',
        size: 'small',
        actionkey: false,
        en: { key: 'k', capsAndKey: 'K', shiftAndKey: 'K' },
        ru: { key: 'л', capsAndKey: 'Л', shiftAndKey: 'Л' },
      },
      {
        code: 'KeyL',
        size: 'small',
        actionkey: false,
        en: { key: 'l', capsAndKey: 'L', shiftAndKey: 'L' },
        ru: { key: 'д', capsAndKey: 'Д', shiftAndKey: 'Д' },
      },
      {
        code: 'Semicolon',
        size: 'small',
        actionkey: false,
        en: { key: ';', capsAndKey: ';', shiftAndKey: ':' },
        ru: { key: 'ж', capsAndKey: 'Ж', shiftAndKey: 'Ж' },
      },
      {
        code: 'Quote',
        size: 'small',
        actionkey: false,
        en: { key: "'", capsAndKey: "'", shiftAndKey: '"' },
        ru: { key: 'э', capsAndKey: 'Э', shiftAndKey: 'Э' },
      },
      {
        code: 'Enter',
        size: 'middle',
        actionkey: true,
        en: { key: 'Enter', capsAndKey: 'Enter', shiftAndKey: 'Enter' },
        ru: { key: 'Enter', capsAndKey: 'Enter', shiftAndKey: 'Enter' },
      },
    ],
    [
      {
        code: 'ShiftLeft',
        size: 'middle',
        actionkey: true,
        en: { key: 'Shift', capsAndKey: 'Shift', shiftAndKey: 'Shift' },
        ru: { key: 'Shift', capsAndKey: 'Shift', shiftAndKey: 'Shift' },
      },
      {
        code: 'KeyZ',
        size: 'small',
        actionkey: false,
        en: { key: 'z', capsAndKey: 'Z', shiftAndKey: 'Z' },
        ru: { key: 'я', capsAndKey: 'Я', shiftAndKey: 'Я' },
      },
      {
        code: 'KeyX',
        size: 'small',
        actionkey: false,
        en: { key: 'x', capsAndKey: 'X', shiftAndKey: 'X' },
        ru: { key: 'ч', capsAndKey: 'Ч', shiftAndKey: 'Ч' },
      },
      {
        code: 'KeyC',
        size: 'small',
        actionkey: false,
        en: { key: 'c', capsAndKey: 'C', shiftAndKey: 'C' },
        ru: { key: 'с', capsAndKey: 'С', shiftAndKey: 'С' },
      },
      {
        code: 'KeyV',
        size: 'small',
        actionkey: false,
        en: { key: 'v', capsAndKey: 'V', shiftAndKey: 'V' },
        ru: { key: 'м', capsAndKey: 'М', shiftAndKey: 'М' },
      },
      {
        code: 'KeyB',
        size: 'small',
        actionkey: false,
        en: { key: 'b', capsAndKey: 'B', shiftAndKey: 'B' },
        ru: { key: 'и', capsAndKey: 'И', shiftAndKey: 'И' },
      },
      {
        code: 'KeyN',
        size: 'small',
        actionkey: false,
        en: { key: 'n', capsAndKey: 'N', shiftAndKey: 'N' },
        ru: { key: 'т', capsAndKey: 'Т', shiftAndKey: 'Т' },
      },
      {
        code: 'KeyM',
        size: 'small',
        actionkey: false,
        en: { key: 'm', capsAndKey: 'M', shiftAndKey: 'M' },
        ru: { key: 'ь', capsAndKey: 'Ь', shiftAndKey: 'Ь' },
      },
      {
        code: 'Comma',
        size: 'small',
        actionkey: false,
        en: { key: ',', capsAndKey: ',', shiftAndKey: '<' },
        ru: { key: 'б', capsAndKey: 'Б', shiftAndKey: 'Б' },
      },
      {
        code: 'Period',
        size: 'small',
        actionkey: false,
        en: { key: '.', capsAndKey: '.', shiftAndKey: '>' },
        ru: { key: 'ю', capsAndKey: 'Ю', shiftAndKey: 'Ю' },
      },
      {
        code: 'Slash',
        size: 'small',
        actionkey: false,
        en: { key: '/', capsAndKey: '/', shiftAndKey: '?' },
        ru: { key: '.', capsAndKey: '.', shiftAndKey: ',' },
      },
      {
        code: 'ArrowUp',
        size: 'small',
        actionkey: false,
        en: { key: '▲', capsAndKey: '▲', shiftAndKey: '▲' },
        ru: { key: '▲', capsAndKey: '▲', shiftAndKey: '▲' },
      },
      {
        code: 'ShiftRight',
        size: 'middle',
        actionkey: true,
        en: { key: 'Shift', capsAndKey: 'Shift', shiftAndKey: 'Shift' },
        ru: { key: 'Shift', capsAndKey: 'Shift', shiftAndKey: 'Shift' },
      },
    ],
    [
      {
        code: 'ControlLeft',
        size: 'small',
        actionkey: true,
        en: { key: 'Ctrl', capsAndKey: 'Ctrl', shiftAndKey: 'Ctrl' },
        ru: { key: 'Ctrl', capsAndKey: 'Ctrl', shiftAndKey: 'Ctrl' },
      },
      {
        code: 'MetaLeft',
        size: 'small',
        actionkey: true,
        en: { key: 'Win', capsAndKey: 'Win', shiftAndKey: 'Win' },
        ru: { key: 'Win', capsAndKey: 'Win', shiftAndKey: 'Win' },
      },
      {
        code: 'AltLeft',
        size: 'small',
        actionkey: true,
        en: { key: 'Alt', capsAndKey: 'Alt', shiftAndKey: 'Alt' },
        ru: { key: 'Alt', capsAndKey: 'Alt', shiftAndKey: 'Alt' },
      },
      {
        code: 'Space',
        size: 'big',
        actionkey: false,
        en: { key: ' ', capsAndKey: ' ', shiftAndKey: ' ' },
        ru: { key: ' ', capsAndKey: ' ', shiftAndKey: ' ' },
      },
      {
        code: 'AltRight',
        size: 'small',
        actionkey: true,
        en: { key: 'Alt', capsAndKey: 'Alt', shiftAndKey: 'Alt' },
        ru: { key: 'Alt', capsAndKey: 'Alt', shiftAndKey: 'Alt' },
      },
      {
        code: 'ArrowLeft',
        size: 'small',
        actionkey: false,
        en: { key: '◄', capsAndKey: '◄', shiftAndKey: '◄' },
        ru: { key: '◄', capsAndKey: '◄', shiftAndKey: '◄' },
      },
      {
        code: 'ArrowDown',
        size: 'small',
        actionkey: false,
        en: { key: '▼', capsAndKey: '▼', shiftAndKey: '▼' },
        ru: { key: '▼', capsAndKey: '▼', shiftAndKey: '▼' },
      },
      {
        code: 'ArrowRight',
        size: 'small',
        actionkey: false,
        en: { key: '►', capsAndKey: '►', shiftAndKey: '►' },
        ru: { key: '►', capsAndKey: '►', shiftAndKey: '►' },
      },
      {
        code: 'ControlRight',
        size: 'small',
        actionkey: true,
        en: { key: 'Ctrl', capsAndKey: 'Ctrl', shiftAndKey: 'Ctrl' },
        ru: { key: 'Ctrl', capsAndKey: 'Ctrl', shiftAndKey: 'Ctrl' },
      },
    ],
  ],
};
